# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80f6e6696a920769d32aa8e947dfaeafda09762fa7af849f08a4a25a8644cc412de1a20bf52b4ce4f42d8f94c7f2a894e189b8ebd907f84edaf51cf67c8f4604

test:
  secret_key_base: 0c903148db17b81be6ba651bad1f9629610f38fc305809c03aa7c9bdca23b563b5efcf18efe822b910e870bfaa7e67d0b8d351fcc24c7721919cfddd8b8c2d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
